Document: dpdk
Title: Debian dpdk Manual
Author: <insert document author here>
Abstract: This manual describes what dpdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dpdk/dpdk.sgml.gz

Format: postscript
Files: /usr/share/doc/dpdk/dpdk.ps.gz

Format: text
Files: /usr/share/doc/dpdk/dpdk.text.gz

Format: HTML
Index: /usr/share/doc/dpdk/html/index.html
Files: /usr/share/doc/dpdk/html/*.html
